# Generated by Django 4.2.5 on 2023-09-06 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date de creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date de modification'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date de creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date de modification'),
        ),
    ]
