# Generated by Django 4.2.5 on 2023-09-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_created_at_choice_update_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='date de modification'),
        ),
        migrations.AlterField(
            model_name='question',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='date de modification'),
        ),
    ]
