# Generated by Django 4.2.5 on 2023-09-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_choice_update_at_alter_question_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
